#pragma once

#define PP_AFE_CHIP_SOFT_PRT_VDIF
#define PP_AFE_CHIP_SOFT_PRT_OHT
#define PP_AFE_CHIP_SOFT_PRT_CELL0_UTD
#define PP_AFE_CHIP_SOFT_PRT_CELL0_UTC
#define PP_AFE_CHIP_SOFT_PRT_CELL0_OTC
#define PP_AFE_CHIP_SOFT_PRT_CELL0_OTD
#define PP_AFE_CHIP_SOFT_PRT_CELL1_UTD
#define PP_AFE_CHIP_SOFT_PRT_CELL1_UTC
#define PP_AFE_CHIP_SOFT_PRT_CELL1_OTC
#define PP_AFE_CHIP_SOFT_PRT_CELL1_OTD
#define PP_AFE_CHIP_SOFT_PRT_UTD
#define PP_AFE_CHIP_SOFT_PRT_UTC
#define PP_AFE_CHIP_SOFT_PRT_OTC
#define PP_AFE_CHIP_SOFT_PRT_OTD
#define PP_AFE_CHIP_SOFT_PRT_OV2
#define PP_AFE_CHIP_SOFT_PRT_UV2
#define PP_AFE_CHIP_SOFT_PRT_MOT
#define PP_AFE_CHIP_SOFT_PRT_CB

#define PP_AFE_CHIP_SOFT_CHGRIN_FLAG_CHK
#define PP_AFE_CHIP_SOFT_CHGROFF_FLAG_CHK
#define PP_AFE_CHIP_SOFT_LDON_FLAG_CHK
#define PP_AFE_CHIP_SOFT_LDOFF_FLAG_CHK

#define PP_AFE_CHIP_I2C_REG_SIZE    1
#define PP_AFE_CHIP_I2C_ADDR        0x20
#define PP_AFE_CHIP_SOFT_OHT_TH     85
#define PP_AFE_CHIP_SOFT_TEMP_HYS   5
#define PP_AFE_CHIP_CYC_TIME        256
