#pragma once

#define _AFE_STATES_FILEDS\
    uint8_t __status_other_begin__;\
    uint8_t afe_chip_init_fail;\
    uint8_t afe_cfg_err;\
    uint8_t can_dsg;\
    uint8_t can_chg;\
    uint8_t chg_mos_status;\
    uint8_t dsg_mos_status;\
    uint8_t pchg_mos_status;\
    uint8_t pdsg_mos_status;\
    uint8_t chgrin_status;\
    uint8_t chgroff_status;\
    uint8_t ldon_status;\
    uint8_t ldoff_status;\
    uint8_t cb_status;\
    uint8_t normal_slp_status;\
    uint8_t __status_other_end__;\
    uint8_t __status_chdsg_begin__;\
    uint8_t fuse_status;\
    uint8_t afe_fail_status;\
    uint8_t vdif_status;\
    uint8_t oht_status;\
    uint8_t mot_status;\
    uint8_t __status_chdsg_end__;\
    uint8_t __status_chg_begin__;\
    uint8_t chgm_fail_status;\
    uint8_t ov1_status;\
    uint8_t ov2_status;\
    uint8_t occ1_status;\
    uint8_t occ2_status;\
    uint8_t occ_status;\
    uint8_t eoc_status;\
    uint8_t cell0_utc_status;\
    uint8_t cell1_utc_status;\
    uint8_t utc_status;\
    uint8_t cell0_otc_status;\
    uint8_t cell1_otc_status;\
    uint8_t otc_status;\
    uint8_t __status_chg_end__;\
    uint8_t __status_dsg_begin__;\
    uint8_t dsgm_fail_status;\
    uint8_t uv1_status;\
    uint8_t uv2_status;\
    uint8_t pdsg_scd_status;\
    uint8_t scd_status;\
    uint8_t ocd1_status;\
    uint8_t ocd2_status;\
    uint8_t ocd_status;\
    uint8_t cell0_utd_status;\
    uint8_t cell1_utd_status;\
    uint8_t utd_status;\
    uint8_t cell0_otd_status;\
    uint8_t cell1_otd_status;\
    uint8_t otd_status;\
    uint8_t __status_dsg_end__;\
