#pragma once

#define PP_DATA_EXPORT_ENV_SYS_SH 1
#define PP_DATA_EXPORT_ENV_SOX_S 2
#define PP_DATA_EXPORT_ENV_AFE_CFG_SH 3
#define PP_DATA_EXPORT_ENV_AFE_SH 4
#define PP_DATA_EXPORT_ENV_SYS_S 5

#define PP_DATA_EXPORT_HOST_BL 1
#define PP_DATA_EXPORT_HOST_SYS 2
#define PP_DATA_EXPORT_HOST_SOX 3
#define PP_DATA_EXPORT_HOST_AFE_VOL 4
#define PP_DATA_EXPORT_HOST_AFE_OTHER 5
#define PP_DATA_EXPORT_HOST_AFE_STATUS 6
#define PP_DATA_EXPORT_HOST_AFE_CFG 7
